Change the updateWidget function to ingest from a byte array
UWARG/Ground-Side-Telemetry pull request #9
Opened 2022-01-26 17:25 UTC by jeffreyli0312

Declared example transmit frame on on_updateWidget_clicked() below:
7E | 00 19 | 10 | 01 | 00 13 A2 00 41 B1 6D 1C | FF FE | 00 | 00 | 53 45 4E 54 20 46 52 4F 4D 20 42 | D1

decoded QByteArray into:
- start deliminator
- frame length, message length
- frame type, frame ID
- 64 bit address
- message
- and check sum

2022-01-26 17:39 UTC, jeffreyli0312 commented on src/mainwindow/mainwindow.cpp
> +    qDebug() << frame_type; // 90 -> 144, 8B -> 139 (to binary)
Leaving qDebug() output function for testing output, will remove after testing decoding works

2022-01-26 17:42 UTC, jeffreyli0312 commented
Mavlink_groundside_decoder has no references in the entire project, I removed it from updateWidget. Is it okay to delete the Mavlink_groundside_decoder function?

2022-01-27 02:40 UTC, rayjinghaolei approved these changes

2022-01-27 02:41 UTC, rayjinghaolei commented
> Mavlink_groundside_decoder has no references in the entire project, I removed it from updateWidget. Is it okay to delete the Mavlink_groundside_decoder function?

I think it is fine

2022-01-27 02:42 UTC, rayjinghaolei commented
@Shrinjay  I don't seem to have the write access to this repo, I guess you will need to do the final confirm and merge

2022-01-30 18:50 UTC, Shrinjay requested changes
Overall, really, really good code, I'm very impressed. Some minor details I noticed but otherwise we're good to merge.

2022-01-30 18:50 UTC, Shrinjay commented on src/mainwindow/mainwindow.cpp
> +void MainWindow::updateWidget(QByteArray encoded_msg) // ex: 7E | 00 19 | 10 | 01 | 00 13 A2 00 41 B1 6D 1C | FF FE | 00 | 00 | 53 45 4E 54 20 46 52 4F 4D 20 42 | D1
Move this comment into the next line

2022-01-30 18:50 UTC, Shrinjay commented on src/mainwindow/mainwindow.cpp
> +
Don't add extra whitespace like this, makes code harder to read

2022-01-30 18:50 UTC, Shrinjay commented on src/mainwindow/mainwindow.ui
> +       <widget class="QPushButton" name="updateWidget">
Following with the above comment, update the name of this button to testUpdateWidget

2022-01-30 18:50 UTC, Shrinjay commented on src/mainwindow/mainwindow.cpp
> +void MainWindow::on_updateWidget_clicked()
Let's avoid confusion and make it clear this is only for testing, change this function to onTestUpdateWidget_clicked and update the button in the .ui file accordingly.

2022-02-14 18:14 UTC, Shrinjay requested changes
Let's just quickly get rid of the video stuff

2022-02-14 18:14 UTC, Shrinjay commented on src/mainwindow/mainwindow.cpp
> +void MainWindow::on_testVideo_clicked()
Can we quickly take the video stuff out of this PR?

2022-02-14 18:50 UTC, merged